### ISSUE TITLE
Installation issues - missing dependencies

### ISSUE THREAD

**Issue by krzyzanowskim** [objcio/swift-talk-backend#92]
The package doesn't build out of the box due to errors from dependencies. This is most likely due to SPM issue that doesn't present providers to the user eg.: https://github.com/PerfectlySoft/Perfect-libxml2/blob/f1c8210504aeeb09ec8a4d0f6d44a05adff3b334/Package.swift#L25

Possible solution:
add `brew install cmark libxml2 postgresql pkg-config` to README, and linux equivalent

**Comment by chriseidhof** [comment]
Thanks @krzyzanowskim! I added a note to the README about the dependencies =)
